import { Investment, DealFlow, PortfolioSummary, DealScore } from './types';

export const mockInvestments: Investment[] = [
  {
    investmentId: '1',
    userId: 'user1',
    companyName: 'TechFlow AI',
    dealSource: 'AngelList',
    investmentAmount: 25000,
    valuation: 5000000,
    dateInvested: '2023-06-15',
    currentValue: 45000,
    status: 'active',
    performanceMetrics: {
      roi: 80,
      irr: 45,
      multiple: 1.8,
      unrealizedGain: 20000,
      realizedGain: 0,
    },
  },
  {
    investmentId: '2',
    userId: 'user1',
    companyName: 'GreenEnergy Solutions',
    dealSource: 'Network',
    investmentAmount: 50000,
    valuation: 8000000,
    dateInvested: '2023-03-20',
    currentValue: 75000,
    status: 'active',
    performanceMetrics: {
      roi: 50,
      irr: 35,
      multiple: 1.5,
      unrealizedGain: 25000,
      realizedGain: 0,
    },
  },
  {
    investmentId: '3',
    userId: 'user1',
    companyName: 'HealthTech Pro',
    dealSource: 'Direct',
    investmentAmount: 30000,
    valuation: 12000000,
    dateInvested: '2023-01-10',
    currentValue: 85000,
    status: 'active',
    performanceMetrics: {
      roi: 183,
      irr: 95,
      multiple: 2.83,
      unrealizedGain: 55000,
      realizedGain: 0,
    },
  },
];

export const mockDeals: DealFlow[] = [
  {
    dealFlowId: '1',
    sourcedBy: 'ai',
    companyName: 'NextGen Robotics',
    description: 'AI-powered robotics for manufacturing automation',
    sourceInfo: 'Sourced from Crunchbase API',
    score: 8.7,
    status: 'new',
    dateSourced: '2024-01-15',
    industry: 'Robotics',
    stage: 'Series A',
    fundingRound: 'Series A - $5M',
    teamSize: 15,
    traction: {
      revenue: 500000,
      growth: 150,
      customers: 25,
      marketSize: 50000000000,
    },
  },
  {
    dealFlowId: '2',
    sourcedBy: 'ai',
    companyName: 'BioMed Analytics',
    description: 'Machine learning for drug discovery acceleration',
    sourceInfo: 'Sourced from PitchBook API',
    score: 9.2,
    status: 'reviewing',
    dateSourced: '2024-01-12',
    industry: 'Biotech',
    stage: 'Seed',
    fundingRound: 'Seed - $2M',
    teamSize: 8,
    traction: {
      revenue: 150000,
      growth: 200,
      customers: 5,
      marketSize: 100000000000,
    },
  },
  {
    dealFlowId: '3',
    sourcedBy: 'network',
    companyName: 'CleanWater Tech',
    description: 'IoT sensors for water quality monitoring',
    sourceInfo: 'Referred by John Smith',
    score: 7.8,
    status: 'interested',
    dateSourced: '2024-01-10',
    industry: 'CleanTech',
    stage: 'Pre-Seed',
    fundingRound: 'Pre-Seed - $500K',
    teamSize: 4,
    traction: {
      revenue: 50000,
      growth: 300,
      customers: 12,
      marketSize: 25000000000,
    },
  },
];

export const mockPortfolioSummary: PortfolioSummary = {
  totalInvested: 105000,
  currentValue: 205000,
  totalROI: 95.2,
  averageIRR: 58.3,
  activeInvestments: 3,
  exitedInvestments: 0,
  topPerformer: mockInvestments[2],
  riskScore: 6.8,
};

export const mockDealScores: Record<string, DealScore> = {
  '1': {
    overall: 8.7,
    team: 8.5,
    market: 9.0,
    product: 8.2,
    traction: 8.8,
    financials: 8.0,
  },
  '2': {
    overall: 9.2,
    team: 9.5,
    market: 9.8,
    product: 9.0,
    traction: 8.5,
    financials: 8.8,
  },
  '3': {
    overall: 7.8,
    team: 7.5,
    market: 8.5,
    product: 7.2,
    traction: 8.8,
    financials: 6.9,
  },
};
